<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FC3_Safety" Id="{d8ed1706-68af-4960-a196-078473d8ccab}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION FC3_Safety : BOOL
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FC3_Safety">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>